language: python
sudo: false
dist: trusty
os:
  - linux
env:
  global:
    secure: "GoXRSfscYO3eVJ8QvCRuqWvLymkdeDbcGujEG9m4xoNtDWhK/AWpKpXCuurgmUglDj6LDjf10zct7YHO+ga3takQNDos9KIx2IWG1xpTGvUYKBm1U9joEq7FfFRc6ZiJnLznKxBvnGN/yL+MCDc39n8UBOa1adiqJFHqVmk6bQGQHDXcAlJSD7HUdfELANHZd4yyMLBwcJtkvuPyipvIB1icV8oR9UbrAYUtrHB3COZV5W4klHe7EK1kF32MMXf5dpwwsLdEuJNO6TpJHCyMqt6/QU9RNBDjfRL6VchGB3bYNbZGx038+aowUBOxQy6d1kSltIJopBjzU09AtkeM8VJbjXL7hHJQv8VE1RVAVmAQPe9UDo2et1RTbmtpEfKG2iR8zx+Wj/o2fIiQIPMKI69cf1op5igKp6N2H9fiupT5sK0QRUp/pPC5S+KBbl/+s5YaN1HXy69tgDPq3yya20cjD5wQ3dk8A8D1Ac3bq1aUBSOFyLwSSMDSOafwsvbSwsSSiu+csRytuHaRW6eGz/1G4jv3HL6nB4135rcVQHtp8CC+QjC8iHGX1wyk28sJg9iMBcaL9hdWwHgTM2dvFM8ErlCY9j1fxZXj7u+CovnAgCKBbsAkJc9chMT5aOFg406BHeGIseeNwgP8qO5G20nazzc0Sw9EAklWl83lm2Q="
  matrix:
    - VERSION="5.1"   WHAT="--lua"
    - VERSION="5.2"   WHAT="--lua"
    - VERSION="5.3"   WHAT="--lua"
    # - VERSION="5.2.0" WHAT="--lua"
    # - VERSION="5.2.1" WHAT="--lua"
    # - VERSION="5.2.2" WHAT="--lua"
    # - VERSION="5.3.0" WHAT="--lua"
    # - VERSION="5.3.1" WHAT="--lua"
    # - VERSION="5.3.2" WHAT="--lua"
    # - VERSION="5.3.3" WHAT="--lua"
    # - VERSION="5.3.4" WHAT="--lua"
    # - VERSION="2.0"   WHAT="--luajit"
    - VERSION="2.0"   WHAT="--luajit" COMPAT="--compat=5.2"
    # - VERSION="2.1"   WHAT="--luajit"
    - VERSION="2.1"   WHAT="--luajit" COMPAT="--compat=5.2"

install:
  - pip install hererocks
  - hererocks --luarocks=^ ${WHAT}=${VERSION} ${COMPAT} ${HOME}/
  - ${HOME}/bin/luarocks make rockspec/environment-master-1.rockspec
  - ${HOME}/bin/luarocks make rockspec/layeredata-master-1.rockspec

script:
  - ${HOME}/bin/luacheck src/
  - ${HOME}/bin/busted   src/
  - ./upload.coveralls || true

jobs:
  include:
    - stage: deploy
      script:
        - ./upload.luarocks

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - alban.linard@gmail.com
  webhooks:
    on_success: always
    on_failure: always
    on_start:   always
    urls:
      - https://webhooks.gitter.im/e/82bbb71c769120136ef3
